### ISSUE TITLE
What is a meta title?

### ISSUE THREAD

**Issue by multiwebinc** [bennothommo/october-plugin-meta#1]
I've never heard of `<meta name="title">` before and according to [this exhaustive list of Meta tags](https://gist.github.com/lancejpollard/1978404), it's not there either. Is this coming from this plugin or from somewhere else?
![image](https://user-images.githubusercontent.com/901732/51216347-bbe05a80-18e9-11e9-8c01-9daa9d5cd566.png)

**Comment by multiwebinc** [comment]
Nevermind, looking at the code I don't think this is from your plugin. Sorry for the confusion.

**Comment by bennothommo** [comment]
@multiwebinc Thanks for the issue report anyway. That field is provided by October CMS directly - I just pass it through to the meta tags if the component is set to include those fields.
